### ISSUE TITLE
Solve the height problem

### ISSUE THREAD

**Issue by killerkc12** [killerkc12/Taskboard#26]
The tasklist should use full page height.
The scrollbar should not come before the screen height.

![image](https://github.com/killerkc12/Taskboard/assets/50802786/b1f601b4-9d25-4391-8cda-74566f81fd60)

**Comment by tsongtheng** [comment]
@killerkc12 , please assign this to me.

**Comment by killerkc12** [comment]
@tsongtheng You can go a head

**Comment by tsongtheng** [comment]
Hi @killerkc12 , ***"The scrollbar should not come before the screen height."***.  What do you mean by this? Can you elaborate?

**Comment by killerkc12** [comment]
@tsongtheng If you see the screenshot.
There is space between screen bottom and tasklist bottom and when task got overloaded scrollbar is started coming.
So tasklist should utilise this space still the bottom of the screen

**Comment by tsongtheng** [comment]
@killerkc12 , should i hide the scroll bar?

**Comment by tsongtheng** [comment]
Is this better? This can still be scrolled when more items are added. I have hide the scroll bar. 
Also I have not given the **tasklist** container a full page height, since it doesn't look good.
- ***Second image*** is when the task list container is given full page height.

#### Image-1
![taskbar-screenshot](https://github.com/killerkc12/Taskboard/assets/69814398/ffa64f81-087c-4ee5-830a-a0cf57413eef)



#### Image-2

![2-img](https://github.com/killerkc12/Taskboard/assets/69814398/854d9c9a-6f76-4e6f-94f7-bf15b245e61c)


## Which one is better?
Both can be scrolled when added more items.

**Comment by killerkc12** [comment]
@tsongtheng Yes, Image-1 looks cool

**Comment by tsongtheng** [comment]
Hi @killerkc12 , I have done the changes but your site is not responsive.  The UI is always going to break at some point when there is no responsiveness.

Should I make it responsive too?

**Comment by killerkc12** [comment]
@tsongtheng Yes. You can create an issue and ask me to assign you.
